import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const outputDir = "outputs/feishu";
const outputPath = `${outputDir}/客户线索-社交软件联系方式-Seed字段对齐.xlsx`;
const collectedAt = "2026-05-27 22:30";

const headers = [
  "线索ID",
  "客户名称",
  "国家",
  "城市/地区",
  "客户类型",
  "线索等级",
  "线索状态",
  "主营车型/业务",
  "是否经营二手/进口车",
  "规模/活跃度信号",
  "联系方式摘要",
  "邮箱",
  "电话",
  "VKontakte",
  "Odnoklassniki",
  "TikTok‌",
  "Max‌",
  "WhatsApp",
  "Telegram",
  "官网",
  "来源平台",
  "来源链接",
  "来源证据备注",
  "渠道风险等级",
  "AI 推荐等级",
  "AI 推荐原因",
  "缺失信息",
  "下一步建议",
  "负责人",
  "交付团队",
  "是否勿扰",
  "勿扰原因",
  "首次采集时间",
  "最近更新时间",
  "人工复核结果",
  "人工复核备注",
];

const leads = [
  {
    name: "Кармакс",
    city: "Moscow",
    grade: "B",
    status: "待复核/可交付客服",
    business: "新车、二手车、电动车销售与服务；车辆可按需求从中国、韩国、美国供应",
    used: "是",
    signal: "公开商户页展示汽车销售、二手车、电动车、进口/按需供应相关业务和电话",
    summary: "电话 + WhatsApp + Telegram",
    email: "Unknown",
    phone: "+7 (926) 456-07-81",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "来源页 Telegram 入口",
    website: "https://carmaxmos.clients.site/",
    platform: "Yandex 商户公开页",
    source: "https://carmaxmos.clients.site/",
    evidence: "页面显示“Автосалон, Продажа автомобилей с пробегом, Электромобили”，并显示“Подписаться на Telegram”“WhatsApp”。",
    risk: "Medium",
  },
  {
    name: "Форза",
    city: "Moscow",
    grade: "B",
    status: "待复核/可交付客服",
    business: "二手车购买、销售、置换、收购和售后相关服务",
    used: "是",
    signal: "公开商户页展示二手车销售、10 年市场经验、电话和多种通讯入口",
    summary: "电话 + WhatsApp + Telegram",
    email: "Unknown",
    phone: "+7 (966) 344-42-24",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "来源页 Telegram 入口",
    website: "https://forzacar.clients.site/",
    platform: "Yandex 商户公开页",
    source: "https://forzacar.clients.site/",
    evidence: "页面显示“Автосалон, Продажа автомобилей с пробегом”，联系方式区域显示 Telegram、Viber、WhatsApp。",
    risk: "Medium",
  },
  {
    name: "Auto zao",
    city: "Moscow",
    grade: "B",
    status: "待复核/可交付客服",
    business: "二手车销售、Trade-in、拍卖车、车辆收购",
    used: "是",
    signal: "公开目录页展示二手车汽车沙龙、电话、官网和 WhatsApp",
    summary: "电话 + WhatsApp",
    email: "Unknown",
    phone: "+7 929 521-00-00; +7 966 048-00-77",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "Unknown",
    website: "https://autozao.ru",
    platform: "公开目录",
    source: "https://orgzz.ru/msk/co/auto_zao/5035167",
    evidence: "公开目录标题为“Автосалон автомобилей с пробегом”，联系方式区域显示两个电话和 WhatsApp。",
    risk: "Low",
  },
  {
    name: "ААРОН-АВТО",
    city: "Moscow",
    grade: "B",
    status: "待复核/可交付客服",
    business: "汽车销售、在库车、按订单车辆、商用车、二手车、电动车和混动车",
    used: "是",
    signal: "官网联系人页展示电话、邮箱和 Telegram 呼叫入口，业务导航包含二手车",
    summary: "邮箱 + 电话 + Telegram",
    email: "info@aaron-auto.ru",
    phone: "+7 (495) 280-77-77",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "Unknown",
    telegram: "来源页 Telegram 呼叫入口",
    website: "https://www.aaron-auto.ru",
    platform: "官网",
    source: "https://www.aaron-auto.ru/kontakty/",
    evidence: "官网联系人页显示“Позвонить в Telegram”、电话、info@aaron-auto.ru，并列出“Автомобили с пробегом”。",
    risk: "Low",
  },
  {
    name: "e.avto",
    city: "Sirius / Sochi",
    grade: "B",
    status: "待复核/可交付客服",
    business: "新车和二手车销售、Trade-in、拍卖车、电动车、车辆收购",
    used: "是",
    signal: "2GIS 公开商户页展示官网、VKontakte 和 WhatsApp，业务含新车和二手车",
    summary: "VKontakte + WhatsApp + 官网",
    email: "Unknown",
    phone: "Unknown",
    vk: "来源页 VKontakte 入口",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "Unknown",
    website: "https://e-avto23.ru",
    platform: "2GIS 地图公开页",
    source: "https://2gis.ru/sochi/firm/70000001094732798",
    evidence: "2GIS 页面显示 e-avto 为“Автосалон”，并显示 e-avto23.ru、ВКонтакте、WhatsApp；业务描述含“Продажа новых легковых машин и авто с пробегом”。",
    risk: "Medium",
  },
  {
    name: "Rekord. Premium",
    city: "Ufa",
    grade: "B",
    status: "待复核/可交付客服",
    business: "二手车销售，汽车沙龙",
    used: "是",
    signal: "2GIS 公开页展示二手车业务、官网、邮箱和 VK/Odnoklassniki/WhatsApp",
    summary: "邮箱 + VKontakte + Odnoklassniki + WhatsApp",
    email: "rekord1avto@yandex.ru",
    phone: "Unknown",
    vk: "来源页 VKontakte 入口",
    ok: "来源页 Odnoklassniki 入口",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "Unknown",
    website: "https://rekordauto.ru",
    platform: "2GIS 地图公开页",
    source: "https://2gis.ru/ufa/firm/70000001038801257",
    evidence: "2GIS 页面显示“Автомобили с пробегом”，并列出 rekordauto.ru、rekord1avto@yandex.ru、ВКонтакте、Одноклассники、WhatsApp。",
    risk: "Medium",
  },
  {
    name: "Эйч Моторс",
    city: "Voronezh",
    grade: "B",
    status: "待复核/可交付客服",
    business: "Voronezh 二手车销售、Trade-in、贷款和服务",
    used: "是",
    signal: "公开商户页展示二手车业务、电话、WhatsApp 和汽车销售评论",
    summary: "电话 + WhatsApp",
    email: "Unknown",
    phone: "+7 (473) 300-39-00",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "Unknown",
    website: "https://hmauto.clients.site/",
    platform: "Yandex 商户公开页",
    source: "https://hmauto.clients.site/",
    evidence: "页面标题/简介显示“Автомобили с пробегом в Воронеже”，联系方式区显示电话和 WhatsApp。",
    risk: "Medium",
  },
  {
    name: "BY CAR Автосалон Сургут",
    city: "Surgut",
    grade: "B",
    status: "待复核/可交付客服",
    business: "二手车销售、贷款、收购、置换和寄售",
    used: "是",
    signal: "公开目录页展示二手车业务、电话和 WhatsApp/Viber 联系方式",
    summary: "电话 + WhatsApp/Viber",
    email: "Unknown",
    phone: "+7 912 816 60 07; +7 (3462) 310-716",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "+7 912 816 60 07",
    telegram: "Unknown",
    website: "https://by-car86.orgs.biz/",
    platform: "公开目录",
    source: "https://by-car86.orgs.biz/",
    evidence: "公开目录页显示“автомобили с пробегом”，并写明“WhatsApp/Viber контакты +7 912 816 60 07”。",
    risk: "Low",
  },
  {
    name: "АВТОЦЕНТР M.A.R.S",
    city: "Barnaul",
    grade: "B",
    status: "待复核/可交付客服",
    business: "二手车销售、车辆寄售、汽车经纪",
    used: "是",
    signal: "公开市场页显示二手车业务、电话和 Telegram 频道线索",
    summary: "电话 + Telegram",
    email: "Unknown",
    phone: "+7 913 210-86-07",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "Unknown",
    telegram: "来源页 Telegram 频道",
    website: "https://skopin.ab-club.ru/brokers/smart_auto/",
    platform: "公开目录",
    source: "https://skopin.ab-club.ru/brokers/smart_auto/",
    evidence: "页面说明“AВТОЦЕНТР M.A.R.S - это проверенные автомобили с пробегом”，并写明视频发布在 Telegram 频道。",
    risk: "Low",
  },
  {
    name: "АвтоПорт",
    city: "Novosibirsk",
    grade: "B",
    status: "待复核/可交付客服",
    business: "新车和二手车销售、车辆收购、贷款、汽车检查",
    used: "是",
    signal: "官网显示 300 多辆在库车、10 年市场经验、电话和 Telegram 频道",
    summary: "电话 + Telegram",
    email: "Unknown",
    phone: "+7 (913) 007-07-01",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "Unknown",
    telegram: "来源页 Telegram 频道",
    website: "https://www.a-port.ru/",
    platform: "官网",
    source: "https://www.a-port.ru/",
    evidence: "官网显示“Более 300 автомобилей”，并写明“Telegram канал АвтоПорт”；业务包含新车和 проверенные автомобили с пробегом。",
    risk: "Low",
  },
  {
    name: "Автоцентр Таганрог",
    city: "Taganrog",
    grade: "B",
    status: "待复核/可交付客服",
    business: "汽车沙龙、车辆收购、二手车销售",
    used: "是",
    signal: "公开商户页展示二手车和新车销售、电话、Telegram 和 WhatsApp",
    summary: "电话 + WhatsApp + Telegram",
    email: "Unknown",
    phone: "+7 (961) 420-50-00",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "来源页 Telegram 入口",
    website: "https://avtocentr-taganrog.clients.site/",
    platform: "Yandex 商户公开页",
    source: "https://avtocentr-taganrog.clients.site/",
    evidence: "页面显示“Автосалон, Выкуп автомобилей, Продажа автомобилей с пробегом”，并显示 Telegram 和 WhatsApp。",
    risk: "Medium",
  },
  {
    name: "КарПро.рф",
    city: "Naberezhnye Chelny",
    grade: "B",
    status: "待复核/可交付客服",
    business: "新车和二手车销售、车辆 подбор/选购服务",
    used: "是",
    signal: "公开目录页展示新车和二手车业务、电话，并在新闻中给出 Telegram 联系链接",
    summary: "电话 + Telegram",
    email: "Unknown",
    phone: "+7 (960) 076-77-48",
    vk: "Unknown",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "Unknown",
    telegram: "https://t.me/carprorf",
    website: "https://carprorf.orgs.biz/",
    platform: "公开目录",
    source: "https://carprorf.orgs.biz/",
    evidence: "公开目录页显示“новых автомобилей ... а также автомобилей с пробегом”，并在新闻中给出 Telegram 链接 https://t.me/carprorf。",
    risk: "Low",
  },
  {
    name: "Autodom",
    city: "Krasnoyarsk",
    grade: "B",
    status: "待复核/可交付客服",
    business: "二手车和按订单车辆销售",
    used: "是",
    signal: "2GIS 公开页展示 Autodom 为二手车和按订单车辆销售，包含邮箱、Telegram、VK、WhatsApp",
    summary: "邮箱 + VKontakte + WhatsApp + Telegram",
    email: "autodomkrsk@gmail.com",
    phone: "Unknown",
    vk: "来源页 VKontakte 入口",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "来源页 Telegram 入口",
    website: "https://автодом24.com",
    platform: "2GIS 地图公开页",
    source: "https://2gis.ru/krasnoyarsk/firm/70000001043822578",
    evidence: "2GIS 页面显示“Autodom — автомобили с пробегом и под заказ”，并列出 Telegram、autodomkrsk@gmail.com、ВКонтакте、WhatsApp。",
    risk: "Medium",
  },
  {
    name: "Vanavto",
    city: "Almetyevsk",
    grade: "B",
    status: "待复核/可交付客服",
    business: "新车和二手车销售",
    used: "是",
    signal: "2GIS 公开页展示新车和二手车业务，包含 Telegram、VKontakte 和 WhatsApp",
    summary: "VKontakte + WhatsApp + Telegram",
    email: "Unknown",
    phone: "Unknown",
    vk: "来源页 VKontakte 入口",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "来源页 Telegram 入口",
    website: "Unknown",
    platform: "2GIS 地图公开页",
    source: "https://2gis.ru/almetevsk/firm/70000001063170958",
    evidence: "2GIS 页面显示“У нас вы найдёте автомобили с пробегом и новые”，并列出 Telegram、ВКонтакте、WhatsApp。",
    risk: "Medium",
  },
  {
    name: "JetAvto",
    city: "Yoshkar-Ola",
    grade: "B",
    status: "待复核/可交付客服",
    business: "二手车销售、Trade-in、新车、车辆收购、试驾",
    used: "是",
    signal: "2GIS 公开页展示二手车业务、邮箱、VK、WhatsApp 和 Viber",
    summary: "邮箱 + VKontakte + WhatsApp",
    email: "jetavto12@yandex.ru",
    phone: "Unknown",
    vk: "来源页 VKontakte 入口",
    ok: "Unknown",
    tiktok: "Unknown",
    max: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "Unknown",
    website: "https://clck.ru/34yLHT",
    platform: "2GIS 地图公开页",
    source: "https://2gis.ru/yoshkarola/firm/70000001079207861",
    evidence: "2GIS 页面显示“Автомобили с пробегом”，并列出 jetavto12@yandex.ru、ВКонтакте、WhatsApp、Viber。",
    risk: "Medium",
  },
];

function rowFromLead(lead, index) {
  const isB = lead.grade === "B";
  return [
    `LEAD-SOC-${String(index + 1).padStart(4, "0")}`,
    lead.name,
    "Russia",
    lead.city,
    "当地车商/二级经销商",
    lead.grade,
    lead.status,
    lead.business,
    lead.used,
    lead.signal,
    lead.summary,
    lead.email,
    lead.phone,
    lead.vk,
    lead.ok,
    lead.tiktok,
    lead.max,
    lead.whatsapp,
    lead.telegram,
    lead.website,
    lead.platform,
    lead.source,
    lead.evidence,
    lead.risk,
    lead.grade,
    isB
      ? "有公开社交软件联系方式、来源链接和车辆销售/二手车经营信号，建议客服人工触达；未发现客户主动询价证据，不进入 C 级。"
      : "有公开社交软件联系方式和车商身份，但二手/进口匹配证据不足，先入库补全。",
    lead.used === "未知" ? "是否经营二手/进口车、采购负责人、目标车型" : "采购负责人、是否采购中国车源、目标车型",
    isB ? "交付客服，仅人工触达；禁止自动社交私信/加好友" : "补全信息，暂不进入触达队列",
    "AI/Agent 操作负责人",
    isB ? "客服" : "线索运营",
    "否",
    "",
    collectedAt,
    collectedAt,
    "待人工复核",
    "AI 仅基于公开文本抽取；社交字段记录公开入口或公开号码，不编造账号。不使用 High/Forbidden 渠道自动任务；不自动私信、不自动加好友。",
  ];
}

function styleSheet(sheet, rowCount, colCount) {
  const all = sheet.getRangeByIndexes(0, 0, rowCount, colCount);
  const header = sheet.getRangeByIndexes(0, 0, 1, colCount);
  header.format.fill.color = "#1F4E78";
  header.format.font.color = "#FFFFFF";
  header.format.font.bold = true;
  all.format.wrapText = true;
  sheet.freezePanes.freezeRows(1);
  const widths = [
    135, 190, 90, 150, 175, 95, 150, 310, 145, 350, 220, 210, 190, 200, 210, 120,
    120, 210, 210, 240, 150, 320, 450, 125, 110, 420, 310, 330, 145, 125, 95, 145,
    160, 160, 140, 440,
  ];
  widths.forEach((width, i) => {
    sheet.getRangeByIndexes(0, i, rowCount, 1).format.columnWidth = width;
  });
}

const workbook = Workbook.create();
const sheet = workbook.worksheets.add("客户线索");
const rows = leads.map(rowFromLead);
const values = [headers, ...rows];
sheet.getRangeByIndexes(0, 0, values.length, headers.length).values = values;
styleSheet(sheet, values.length, headers.length);

await fs.mkdir(outputDir, { recursive: true });
const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(outputPath);

console.log(JSON.stringify({
  outputPath,
  rows: rows.length,
  columns: headers.length,
  gradeDistribution: rows.reduce((acc, row) => {
    acc[row[5]] = (acc[row[5]] ?? 0) + 1;
    return acc;
  }, {}),
}, null, 2));
