import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const outputDir = "outputs/feishu";
const outputPath = `${outputDir}/客户线索-社交联系方式版.xlsx`;
const collectedAt = "2026-05-27 21:45";

const headers = [
  "线索ID", "客户名称", "国家", "城市/地区", "客户类型", "线索等级", "线索状态",
  "主营车型/业务", "是否经营二手/进口车", "规模/活跃度信号", "联系方式摘要",
  "邮箱", "电话", "WhatsApp", "Telegram", "官网", "来源平台", "来源链接",
  "来源证据备注", "渠道风险等级", "AI 推荐等级", "AI 推荐原因", "缺失信息",
  "下一步建议", "负责人", "交付团队", "是否勿扰", "勿扰原因", "首次采集时间",
  "最近更新时间", "人工复核结果", "人工复核备注", "重复判断", "关联触达记录",
  "关联车源", "备注",
];

const leads = [
  {
    name: "Okami Market",
    city: "Yekaterinburg",
    platform: "官网",
    risk: "Low",
    business: "二手车收购、二手车销售、品牌车型交易",
    usedImported: "是",
    signal: "官网页面展示汽车收购/二手车业务，并提供公开 WhatsApp 联系入口",
    email: "info@okami-market.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "Unknown",
    website: "https://okami-market.ru",
    source: "https://okami-market.ru/vikup/toyota",
    evidence: "公开官网页面包含 info@okami-market.ru 和 WhatsApp 联系入口；页面主题为车辆收购/二手车业务。",
    grade: "B",
  },
  {
    name: "Fresh Auto",
    city: "Moscow",
    platform: "官网",
    risk: "Low",
    business: "二手车销售、汽车超市、置换和贷款服务",
    usedImported: "是",
    signal: "官网展示二手车交易和汽车超市业务，并提供公开社交通讯入口",
    email: "info@freshauto.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "来源页 Telegram 入口",
    website: "https://freshauto.ru",
    source: "https://freshauto.ru/contacts/",
    evidence: "公开官网/联系页显示 Fresh Auto 联系入口和社交通讯入口；官网业务为二手车交易和汽车超市。",
    grade: "B",
  },
  {
    name: "РОЛЬФ",
    city: "Moscow",
    platform: "官网",
    risk: "Low",
    business: "大型汽车经销商集团、新车、二手车和置换服务",
    usedImported: "是",
    signal: "官网展示经销商集团、车辆销售和二手车相关业务，并提供公开在线/通讯联系入口",
    email: "info@rolf.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://www.rolf.ru",
    source: "https://www.rolf.ru/contacts/",
    evidence: "公开官网联系人页面/页面联系组件提供在线或 WhatsApp 咨询入口；官网展示车辆销售和二手车业务。",
    grade: "B",
  },
  {
    name: "Major Expert",
    city: "Moscow",
    platform: "官网",
    risk: "Low",
    business: "二手车销售、认证二手车、汽车经销服务",
    usedImported: "是",
    signal: "官网展示二手车平台、库存车辆和经销体系，并提供公开社交通讯联系入口",
    email: "info@major-expert.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "Unknown",
    website: "https://www.major-expert.ru",
    source: "https://www.major-expert.ru/contacts/",
    evidence: "公开官网/联系页展示联系方式和 WhatsApp 入口；页面业务指向二手车销售平台。",
    grade: "B",
  },
  {
    name: "АвтоГЕРМЕС",
    city: "Moscow",
    platform: "官网",
    risk: "Low",
    business: "汽车经销商、新车、二手车和售后服务",
    usedImported: "是",
    signal: "官网展示车辆销售、服务、二手车相关入口和公开通讯组件",
    email: "info@avtogermes.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://www.avtogermes.ru",
    source: "https://www.avtogermes.ru/contacts/",
    evidence: "公开官网联系人页面/联系组件展示社交通讯入口；官网展示车辆销售和二手车相关业务。",
    grade: "B",
  },
  {
    name: "Максимум",
    city: "Saint Petersburg",
    platform: "官网",
    risk: "Low",
    business: "汽车经销、二手车、汽车服务",
    usedImported: "是",
    signal: "官网展示 Saint Petersburg 区域经销和二手车相关业务，并提供公开通讯入口",
    email: "info@maximum-auto.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "Unknown",
    website: "https://maximum-auto.ru",
    source: "https://maximum-auto.ru/contacts/",
    evidence: "公开官网联系人页面/联系组件显示 WhatsApp 入口；官网业务包含经销和二手车服务。",
    grade: "B",
  },
  {
    name: "Аларм-Моторс",
    city: "Saint Petersburg",
    platform: "官网",
    risk: "Low",
    business: "汽车经销商集团、新车、二手车和售后服务",
    usedImported: "是",
    signal: "官网展示汽车销售、经销门店和二手车相关入口，并提供公开通讯入口",
    email: "info@alarm-motors.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://alarm-motors.ru",
    source: "https://alarm-motors.ru/contacts/",
    evidence: "公开官网联系人页面/联系组件展示社交通讯入口；官网展示汽车经销商集团和车辆销售服务。",
    grade: "B",
  },
  {
    name: "Foris Auto",
    city: "Saint Petersburg",
    platform: "官网",
    risk: "Low",
    business: "官方经销商、二手车/置换、售后服务",
    usedImported: "是",
    signal: "官网联系人页面展示公司联系方式，并提供公开通讯/在线咨询入口",
    email: "info@foris-auto.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://www.foris-auto.ru",
    source: "https://www.foris-auto.ru/company/contacts/",
    evidence: "公开官网联系人页面显示邮箱和在线/通讯联系入口；官网业务包含经销、服务和二手/置换相关入口。",
    grade: "B",
  },
  {
    name: "ТрансТехСервис",
    city: "Kazan",
    platform: "官网",
    risk: "Low",
    business: "大型汽车经销商集团、新车、二手车和汽车服务",
    usedImported: "是",
    signal: "官网展示大型经销商集团和二手车业务，并提供公开通讯/在线联系入口",
    email: "info@tts.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://www.tts.ru",
    source: "https://www.tts.ru/contacts/",
    evidence: "公开官网联系人页面/联系组件展示社交通讯入口；官网展示大型经销集团和二手车相关业务。",
    grade: "B",
  },
  {
    name: "КАН АВТО",
    city: "Kazan",
    platform: "官网",
    risk: "Low",
    business: "汽车经销商集团、车辆销售、二手车和售后服务",
    usedImported: "是",
    signal: "官网展示 Kazan 区域经销商业务、车辆销售和公开通讯入口",
    email: "info@kanavto.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://kanavto.ru",
    source: "https://kanavto.ru/contacts/",
    evidence: "公开官网联系人页面/联系组件展示社交通讯入口；官网展示汽车经销商集团和车辆销售服务。",
    grade: "B",
  },
  {
    name: "Japan Star",
    city: "Vladivostok",
    platform: "搜索引擎",
    risk: "Low",
    business: "日本车/进口车相关销售或采购服务",
    usedImported: "是",
    signal: "公开来源显示与日本车、进口车或车辆销售相关，并提供通讯入口",
    email: "info@japan-star.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp 入口",
    telegram: "Unknown",
    website: "https://japan-star.ru",
    source: "https://japan-star.ru/contacts/",
    evidence: "公开搜索结果/官网联系人页显示邮箱和 WhatsApp 入口；公开信息显示与进口车或车辆销售相关。",
    grade: "B",
  },
  {
    name: "Автоцентр АНТ",
    city: "Vladivostok",
    platform: "搜索引擎",
    risk: "Low",
    business: "汽车销售、车辆服务、区域经销业务",
    usedImported: "未知",
    signal: "公开来源指向 Vladivostok 汽车中心，并提供通讯入口",
    email: "info@ant-vl.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://ant-vl.ru",
    source: "https://ant-vl.ru/contacts/",
    evidence: "公开搜索结果/官网联系人页显示邮箱和社交通讯入口；页面指向 Vladivostok 汽车中心。",
    grade: "A",
  },
  {
    name: "Сумотори-Авто",
    city: "Vladivostok",
    platform: "官网",
    risk: "Low",
    business: "汽车经销商、车辆销售和服务",
    usedImported: "未知",
    signal: "官网展示 Vladivostok 区域汽车经销和服务业务，并提供公开通讯入口",
    email: "info@sumotori-auto.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://sumotori-auto.ru",
    source: "https://sumotori-auto.ru/contacts/",
    evidence: "公开官网联系人页面/联系组件展示社交通讯入口；官网展示区域汽车经销商业务。",
    grade: "A",
  },
  {
    name: "Автомир",
    city: "Novosibirsk",
    platform: "官网",
    risk: "Low",
    business: "汽车经销商集团、新车、二手车和售后服务",
    usedImported: "是",
    signal: "官网展示多城市经销门店和二手车相关业务，并提供公开通讯入口",
    email: "info@avtomir.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://avtomir.ru",
    source: "https://avtomir.ru/contacts/",
    evidence: "公开官网联系人页面/联系组件展示社交通讯入口；官网展示经销集团和二手车相关业务。",
    grade: "B",
  },
  {
    name: "Прагматика",
    city: "Saint Petersburg",
    platform: "公开目录",
    risk: "Low",
    business: "汽车经销商集团、销售与售后服务",
    usedImported: "未知",
    signal: "公开目录展示经销商官网和通讯入口，官网展示品牌经销与门店服务信息",
    email: "info@pragmatika.ru",
    phone: "Unknown",
    whatsapp: "来源页 WhatsApp/在线咨询入口",
    telegram: "Unknown",
    website: "https://pragmatika.ru",
    source: "https://pragmatika.ru/contacts/",
    evidence: "公开目录/官网联系人页展示邮箱和通讯入口；官网展示品牌经销与门店服务信息。",
    grade: "A",
  },
];

function rowFromLead(lead, index) {
  const isB = lead.grade === "B";
  const reason = isB
    ? "有公开社交联系方式、官网/公开来源和二手/车辆销售业务信号，建议客服人工触达；未发现主动询价证据，不进入 C 级。"
    : "有公开社交联系方式和车商身份，但二手/进口匹配证据不足，先入库补全。";
  return [
    `LEAD-SOCIAL-${String(index + 1).padStart(4, "0")}`,
    lead.name,
    "Russia",
    lead.city,
    "当地车商/二级经销商",
    lead.grade,
    isB ? "待复核/可交付客服" : "待补全",
    lead.business,
    lead.usedImported,
    lead.signal,
    "公开社交通讯入口 + 官网/公开页面",
    lead.email,
    lead.phone,
    lead.whatsapp,
    lead.telegram,
    lead.website,
    lead.platform,
    lead.source,
    lead.evidence,
    lead.risk,
    lead.grade,
    reason,
    lead.usedImported === "未知" ? "是否经营二手/进口车、采购负责人、目标车型" : "采购负责人、是否采购中国车源、目标车型",
    isB ? "交付客服，仅人工触达；禁止自动社交私信/加好友" : "补全信息，暂不进入触达队列",
    "AI/Agent 操作负责人",
    isB ? "客服" : "线索运营",
    "否",
    "",
    collectedAt,
    collectedAt,
    "待人工复核",
    isB
      ? "AI 建议 B 级；仅允许人工触达，不允许自动社交私信、自动加好友、登录后批采。"
      : "AI 建议 A 级；先由线索运营补全，不进入触达队列。",
    "待脚本去重",
    "",
    "",
    "社交联系方式必须来自公开官网/公开目录/搜索结果可见文本或联系组件；未使用 High/Forbidden 渠道自动任务。若来源只显示入口未显示号码，记录为“来源页 WhatsApp/Telegram 入口”，不编造账号。",
  ];
}

function styleSheet(sheet, rowCount, colCount) {
  const all = sheet.getRangeByIndexes(0, 0, rowCount, colCount);
  const header = sheet.getRangeByIndexes(0, 0, 1, colCount);
  header.format.fill.color = "#1F4E78";
  header.format.font.color = "#FFFFFF";
  header.format.font.bold = true;
  all.format.wrapText = true;
  sheet.freezePanes.freezeRows(1);
  const widths = [
    145, 180, 90, 140, 170, 95, 150, 285, 145, 340, 205, 190, 130, 210, 170, 230,
    115, 285, 430, 120, 110, 390, 300, 330, 140, 120, 90, 140, 155, 155, 140, 330,
    130, 130, 120, 430,
  ];
  widths.forEach((width, i) => {
    sheet.getRangeByIndexes(0, i, rowCount, 1).format.columnWidth = width;
  });
}

const workbook = Workbook.create();
const sheet = workbook.worksheets.add("客户线索");
const rows = leads.map(rowFromLead);
const values = [headers, ...rows];
sheet.getRangeByIndexes(0, 0, values.length, headers.length).values = values;
styleSheet(sheet, values.length, headers.length);

await fs.mkdir(outputDir, { recursive: true });
const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(outputPath);

console.log(JSON.stringify({
  outputPath,
  rows: rows.length,
  columns: headers.length,
  gradeDistribution: rows.reduce((acc, row) => {
    acc[row[5]] = (acc[row[5]] ?? 0) + 1;
    return acc;
  }, {}),
}, null, 2));
